<?php

/*TODO: Write a SQL query to retrieve all the customer 
information along with the total number of orders placed by each 
customer. Display the result in descending order of the number of 
orders.*/

//Initializing effort to Connect to a permitted server/database :

$hostname= "127.0.0.1";
$username= "root";
$password="----";
$database="----";

$mysqli= new mysqli($hostname, $username, $password, $database);

//Data Retrieving Effort (For TASK-1):

if($mysqli->connect_error){
    echo "Failed to Connect"}
else{
    $sql = "SELECT
    c.customer_id,
    c.name,
    c.email,
    c.location,
    COUNT(o.order_id) AS total_orders
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name, c.email, c.location
ORDER BY total_orders DESC";

$result= $mysqli->query($sql);

echo $result;

}




/*TODO:  Write a SQL query to retrieve the product name, 
quantity, and total amount for each order item. 
Display the result in ascending order of the order ID.*/


//Data Retrieving Effort (For TASK-2):

if($mysqli->connect_error){
    echo "Failed to Connect"}
else{
    $sql = "SELECT
    p.name AS product_name,
    oi.quantity,
    oi.quantity * oi.unit_price AS total_amount
FROM Order_Items oi
JOIN Products p ON oi.product_id = p.product_id
ORDER BY oi.order_id ASC";

$result= $mysqli->query($sql);

echo $result;

}



/*TODO: Write a SQL query to retrieve the total revenue 
generated by each product category. Display the category name along 
with the total revenue in descending order of the revenue.*/


//Data Retrieving Effort (For TASK-3):

if($mysqli->connect_error){
    echo "Failed to Connect"}
else{
    $sql = "SELECT
    c.name AS category_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM Categories c
LEFT JOIN Products p ON c.category_id = p.category_id
LEFT JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY c.name
ORDER BY total_revenue DESC";

$result= $mysqli->query($sql);

echo $result;

}





/*TODO:  Write a SQL query to retrieve the top 5 customers 
who have made the highest total purchase amount. 
Display the customer name along with the total purchase amount 
in descending order of the purchase amount.*/


//Data Retrieving Effort (For TASK-4):

if($mysqli->connect_error){
    echo "Failed to Connect"}
else{
    $sql = "SELECT
    c.name AS customer_name,
    SUM(oi.quantity * oi.unit_price) AS 

total_purchase_amount
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
LEFT JOIN Order_Items oi ON o.order_id = oi.order_id
GROUP BY c.name
ORDER BY total_purchase_amount DESC
LIMIT 5";

$result= $mysqli->query($sql);

echo $result;

}


//Closing the server/database connection :

$mysqli->close();


?>